# Generated by Django 5.0.4 on 2024-04-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="giftcardids",
            field=models.JSONField(blank=True, default="{}", null=True),
        ),
    ]
