# Generated by Django 5.0.4 on 2024-04-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "block",
                    models.CharField(
                        blank=True, db_column="Block", max_length=7, null=True
                    ),
                ),
                (
                    "shelf",
                    models.CharField(
                        blank=True, db_column="Shelf", max_length=1, null=True
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        blank=True, db_column="Level", max_length=7, null=True
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True, db_column="ProductName", max_length=42, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        db_column="Price",
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, db_column="Unit", max_length=5, null=True
                    ),
                ),
                (
                    "stock",
                    models.DecimalField(
                        blank=True,
                        db_column="Stock",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "product_id",
                    models.CharField(
                        blank=True, db_column="ProductID", max_length=36, null=True
                    ),
                ),
                (
                    "product_pic_path",
                    models.CharField(
                        blank=True, db_column="ProductPicPath", max_length=62, null=True
                    ),
                ),
            ],
            options={
                "db_table": "Products",
            },
        ),
    ]
