# Generated by Django 5.0.4 on 2024-04-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Block", models.CharField(max_length=100)),
                ("Shelf", models.CharField(max_length=100)),
                ("Level", models.CharField(max_length=100)),
                ("ProductName", models.CharField(max_length=100)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Unit", models.CharField(max_length=100)),
                ("Stock", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ProductID", models.TextField()),
                ("ProductPicPath", models.CharField(max_length=255)),
            ],
        ),
    ]
