# Generated by Django 5.0.4 on 2024-04-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managegoods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Level",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="Shelf",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
