# Generated by Django 5.0.4 on 2024-04-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("managegoods", "0002_alter_product_level_alter_product_shelf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="ProductPicPath",
            field=models.CharField(default="", max_length=255, null=True),
        ),
    ]
